/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        background: '#f5faf8',
        surface: '#f5faf8',
        'surface-bright': '#f5faf8',
        'surface-dim': '#d6dbd9',
        'surface-variant': '#dee4e1',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f0f5f2',
        'surface-container': '#eaefed',
        'surface-container-high': '#e4e9e7',
        'surface-container-highest': '#dee4e1',
        'inverse-surface': '#2c3130',
        'inverse-on-surface': '#edf2f0',
        primary: '#00685f',
        'primary-container': '#008378',
        'primary-fixed': '#89f5e7',
        'primary-fixed-dim': '#6bd8cb',
        'on-primary': '#ffffff',
        'on-primary-container': '#f4fffc',
        'on-primary-fixed': '#00201d',
        'on-primary-fixed-variant': '#005049',
        'inverse-primary': '#6bd8cb',
        'surface-tint': '#006a61',
        secondary: '#645d58',
        'secondary-container': '#eae1da',
        'secondary-fixed': '#eae1da',
        'secondary-fixed-dim': '#cec5bf',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#6a635e',
        'on-secondary-fixed': '#1f1b17',
        'on-secondary-fixed-variant': '#4b4641',
        tertiary: '#924628',
        'tertiary-container': '#b05e3d',
        'tertiary-fixed': '#ffdbce',
        'tertiary-fixed-dim': '#ffb59a',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#fffbff',
        'on-tertiary-fixed': '#370e00',
        'on-tertiary-fixed-variant': '#773215',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'on-background': '#171d1c',
        'on-surface': '#171d1c',
        'on-surface-variant': '#3d4947',
        outline: '#6d7a77',
        'outline-variant': '#bcc9c6',
        'green-50': '#F0FDF4',
        'green-600': '#16A34A',
        'red-50': '#FEF2F2',
        'red-600': '#DC2626',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        margin: '20px',
        base: '4px',
        gutter: '16px',
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
      },
      fontFamily: {
        display: ['Plus Jakarta Sans', 'sans-serif'],
        h1: ['Plus Jakarta Sans', 'sans-serif'],
        h2: ['Plus Jakarta Sans', 'sans-serif'],
        h3: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        small: ['Inter', 'sans-serif'],
        micro: ['Inter', 'sans-serif'],
      },
      fontSize: {
        display: ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '700' }],
        h1: ['22px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '700' }],
        h2: ['18px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '600' }],
        h3: ['16px', { lineHeight: '22px', letterSpacing: '0em', fontWeight: '600' }],
        body: ['15px', { lineHeight: '22px', letterSpacing: '0em', fontWeight: '400' }],
        small: ['13px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '400' }],
        micro: ['11px', { lineHeight: '14px', letterSpacing: '0.03em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}

